# -*- coding: utf-8 -*-
"""Andre Apriyana-0110221111-TI04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ar1QGMzMHwPAkQjBWrFVzrRtfyVEjQP9
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
# %matplotlib inline

GRAY1, GRAY2, GRAY3 = '#231F20', '#414040', '#555655'
GRAY4, GRAY5, GRAY6 = '#646369', '#76787B', '#828282'
GRAY7, GRAY8, GRAY9 = '#929497', '#A6A6A5', '#BFBEBE'
BLOODRED1, BLOODRED2, BLOODRED3, BLOODRED4 = '#660000', '#660000', '#660000', '#660000'
RED1, RED2 = '#C3514E', '#E6BAB7'
GREEN1, GREEN2 = '#0C8040', '#9ABB59'
ORANGE1 = '#F79747'

X = ['2013', '2014', '2015']
YMI = np.array([5, 3, 8, 6, 5, 6, 12, 15, 20, 33, 42])
YME = np.array([54, 62, 67, 69, 74, 55, 60, 59, 68, 61, 45])
YE = np.array([41, 35, 25, 25, 21, 39, 28, 26, 12, 6, 13])

fig, ax1 = plt.subplots(figsize=(9.5, 7.2), # width, height in inches
 dpi=110)
fig.subplots_adjust(left=0.103, right=0.7, top=0.881, bottom=0.096)

ax1.set_ylim([0, 100])
ax1.set_xlim([0, 11])

ax1.spines['bottom'].set_position('zero')

plt.bar(list(range(0, 11)), YMI + YME + YE, width=0.60, color=RED1,
 edgecolor=ORANGE1, linewidth=1)


white_bars = plt.bar(list(range(0, 11)), YE, width=0.60,
 color='#5D8AA8', edgecolor=ORANGE1, linewidth=1)

white_bars = plt.bar(list(range(0, 11)), YME + YMI, width=0.60,
 color='#B9D9EB', edgecolor=ORANGE1, linewidth=1)

white_bars = plt.bar(list(range(0, 11)), YMI , width=0.60,
 color='#660000', edgecolor=ORANGE1, linewidth=1)

#jumlah persen
ax1.text(-1, 50, '% of total projects', fontsize=17.5, rotation='vertical',
 color=GRAY7)

#judul bar
plt.text(0, 110, 'Goal Attainment over time',
 fontsize=20, color=GRAY4)

#kategori warna bar
plt.text(0, 105, 'MISS',
 fontsize=10, color='#660000')

plt.text(2, 105, 'MEET',
 fontsize=10, color='#5D8AA8')

plt.text(4, 105, 'EXCEED',
 fontsize=10, color='#2e5090')

#Q1-4

plt.text(0, -6, 'Q1|',
 fontsize=12, color='black')

plt.text(1, -6, 'Q2|',
 fontsize=12, color='black')

plt.text(2, -6, 'Q3|',
 fontsize=12, color='black')

plt.text(3, -6, 'Q4|',
 fontsize=12, color='black')

plt.text(4, -6, 'Q1|',
 fontsize=12, color='black')

plt.text(5, -6, 'Q2|',
 fontsize=12, color='black')

plt.text(6, -6, 'Q3|',
 fontsize=12, color='black')

plt.text(7, -6, 'Q4|',
 fontsize=12, color='black')

plt.text(8, -6, 'Q1|',
 fontsize=12, color='black')

plt.text(9, -6, 'Q2|',
 fontsize=12, color='black')

plt.text(10, -6, 'Q3|',
 fontsize=12, color='black')

#tahun
plt.text(1, -10, '|  2013  |',
 fontsize=12, color='gray')

plt.text(4, -10, '|  2014  |',
 fontsize=12, color='gray')

plt.text(7, -10, '|  2015  |',
 fontsize=12, color='gray')